AWSTemplateFormatVersion: 2010-09-09
Description: Monitoring and logging for Merck DevOps Challenge

Parameters:
  Environment:
    Type: String
    AllowedValues: [d, s, p]
    Description: Environment (d=dev, s=staging, p=prod)

  ECSClusterName:
    Type: String
    Description: ECS Cluster Name

  ECSServiceName:
    Type: String
    Description: ECS Service Name

Resources:
  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub ${Environment}-merck-devops-challenge-dashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/ECS", "CPUUtilization", "ServiceName", "d-devops-challenge-ecs-service", "ClusterName", "d-devops-challenge-ecs-cluster" ],
                  [ ".", "MemoryUtilization", ".", ".", ".", "." ]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "ECS Service Metrics"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/ApplicationELB", "RequestCount", "LoadBalancer", "d-devops-challenge-alb" ],
                  [ ".", "TargetResponseTime", ".", "." ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Load Balancer Metrics"
              }
            }
          ]
        }

  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub d-devops-challenge-high-cpu-alarm
      AlarmDescription: High CPU utilization alarm
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value: !Sub d-devops-challenge-ecs-service
        - Name: ClusterName
          Value: !Sub d-devops-challenge-ecs-cluster

Outputs:
  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=d-devops-challenge-dashboard
