AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure-only deployment for Merck DevOps Challenge

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  # ECR Repository first
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: merck-devopsch-api
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: false

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested/network/network.yml
      Parameters:
        Environment: !Ref Environment

  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: nested/monitoring/monitoring.yml
      Parameters:
        Environment: !Ref Environment

Outputs:
  ECRRepositoryURI:
    Description: ECR Repository URI
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub ${Environment}-ECR-Repository-URI