AWSTemplateFormatVersion: 2010-09-09
Description: Secrets Manager for demo user credentials

Parameters:
  Environment:
    Type: String
    AllowedValues: [d, s, p]
    Description: Environment (d=dev, s=staging, p=prod)

Resources:
  DemoUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${Environment}-merck-devops-challenge-demo-user
      Description: Demo user credentials for Cognito
      GenerateSecretString:
        SecretStringTemplate: '{"username": "krishna3w4@gmail.com"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
        RequireEachIncludedType: true

Outputs:
  SecretArn:
    Description: Demo user secret ARN
    Value: !Ref DemoUserSecret

  SecretName:
    Description: Demo user secret name
    Value: !Ref DemoUserSecret